MuralDevKit/mural-integrations-sdk

packages/mural-client/src/fetch.ts

This PR makes the session cleanup logic in the mural-client fetch handler more lenient for non catastrophic errors.

[ECO-77] Fix mural-client destroying the session prematurely

---

packages/mural-client/src/index.ts

This PR fixes the mural-client builder from not properly using the default values (i.e. `secure: true`) when the override was not supplied.
As a workaround simply send `secure: true` when building the `ApiClient`.

[ECO-79] Fix mural-client defaults handling

---

packages/mural-picker/src/components/card-list/index.tsx

**Description**
Fix bug when there are no murals (new account), the 'Create new mural' button was not displayed
**Jira**
https://mural.atlassian.net/browse/MI-722

[MI-722] Fix 'new mural' button not displayed when no murals

---

package-lock.json
package.json
packages/mural-account-chooser/package-lock.json
packages/mural-account-chooser/package.json
test/package.json

Since you created your branch from `fix/mi-591` we should be able to merge your changes into my branch, right? Easier than cherry-picking.

Fix dependencies

---

packages/mural-client/src/index.ts
packages/mural-client/src/types.ts

https://mural.atlassian.net/browse/MI-741
Add updateStickyNote endpoint
https://github.com/tactivos/mural-integrations/pull/788

[MI-741] Add updateStickyNote endpoint

---

packages/mural-account-chooser/src/components/account-chooser/index.tsx

The PM made this request, and he's the primary consumer of the events at this point.

Update tracking events for account chooser [MI-780]

---

packages/mural-common/styles/common.scss
packages/mural-picker/src/components/card-list-item/generic.tsx
packages/mural-picker/src/components/card-list-item/styles.scss
packages/mural-picker/src/components/card-list-item/types.ts
packages/mural-picker/src/components/card-list/card-list-section.tsx
packages/mural-picker/src/components/mural-create/styles.scss
packages/mural-picker/src/components/mural-picker-modal/styles.scss
packages/mural-picker/src/components/mural-select/styles.scss
packages/mural-picker/src/components/room-select/styles.scss
packages/mural-picker/src/components/workspace-select/styles.scss
packages/mural-picker/src/index.ts

https://github.com/MuralDevKit/mural-integrations-sdk/pull/86 except implemented differently.

Export Mural Card from Mural Picker [MI-758]

---

packages/mural-picker/src/components/card-list-item/styles.scss
packages/mural-picker/src/components/card-list/styles.scss
storybook/stories/mural-picker.stories.tsx

We have issue in Prod now with the layout of Mural-picker.
this one will fix those and also adds a story for the picker

Fix Mural-picker layout 

---

packages/mural-picker/features/mural-picker.feature
packages/mural-picker/src/components/mural-picker/index.tsx
storybook/stories/mural-picker.stories.tsx
test/react/pages/mural-picker.tsx
test/react/step-definitions/given/misc.ts

Add disableCreate flag to mural-picker to hide the '+ New Mural' button.

[MI-875] Add/mi 875

---

packages/mural-canvas/src/components/canvas/index.tsx
packages/mural-canvas/src/lib/rpc.ts
packages/mural-canvas/src/lib/session-activation.ts
sample/src/app-automation.tsx
sample/src/app-basic.tsx

JIRA: [ECO-511](https://mural.atlassian.net/browse/ECO-511)
Add `postMessage`-based session activation flow.

[ECO-511] Add postMessage-based session activation flow

---

packages/mural-client/src/index.ts
tsconfig.json

Update to es2022

---

packages/mural-client/src/fetch.ts

This PR is fixing some issues we have with `authenticatedFetch`. The problems were:
- If multiple requests are issued at the same time, it was possible to refresh the same token more than once
- 'Need to refresh' is not a valid error anymore for public API, so if token is expired, the token was not refreshed
Improvements are:
- Making sure a token can be refreshed only once by using the same Promise (with `memoize`)
- Replacing  'Need to refresh' check by making sure there's enough time left to issue a request

Improve refresh token in authenticatedFetch

---

packages/mural-client/src/index.ts

Adding types and options to create Mural in Mural Client

[MI-1015] Add types to createMural

---

packages/mural-picker/src/components/mural-create/index.tsx

Add infinite argument to create mural in picker

Add infinite argument to create mural in picker

---

packages/mural-client/src/fetch.ts

https://mural.atlassian.net/browse/MI-1050
Fix bug with memoized refresh token

Fix bug with memoized refresh token

---

packages/mural-picker/src/components/mural-picker/index.tsx
packages/mural-picker/src/components/workspace-select/index.tsx

Mural Picker - Making sure requests are done before switching tabs

Mural Picker - Making sure requests are done before switching tabs

---

packages/mural-picker/src/components/card-list-item/styles.scss
packages/mural-picker/src/components/mural-picker/styles.scss

Update card title and details CSS
https://mural.atlassian.net/browse/MI-1053
https://www.figma.com/file/8GjdMb7GRMT9k342xYZhYn/Mural-Picker-Hana%2B-Ideation?node-id=480%3A16444&mode=dev
**Before**:
**After**:

[MI-1053] Update card title and details CSS

---

packages/mural-canvas/src/components/canvas/index.tsx

Add `onInvalidInvitation` event to Canvas component
https://mural.atlassian.net/browse/MI-1061

[MI-1061] Add onInvalidInvitation event to Canvas component

---

packages/mural-picker/src/components/mural-picker/styles.scss

https://mural.atlassian.net/browse/MI-1066
Improve mural picker dark mode

[MI-1066] Improve mural picker dark mode

---

packages/mural-client/src/index.ts

Add `getMuralUsers` and `getRoom` endpoints
https://mural.atlassian.net/browse/MI-1042

[MI-1042] Add getMuralUsers and getRoom endpoints

---

packages/mural-client/src/index.ts

We needed to update the SDK based on this PR: https://github.com/tactivos/mural-api/pull/10066/files
I tested it locally and it works!
[Jira Ticket](https://mural.atlassian.net/browse/CWI-216)

CWI-216 - Messaging Extension - Update the endpoint in SDK to support the new date parameters

---

packages/mural-client/src/index.ts

Messaging Extension - Update the endpoint in SDK to support createdBy and withMembers
https://mural.atlassian.net/browse/CWI-233

CWI-233 Messaging Extension - Update the endpoint in SDK to support createdBy and withMembers

---

packages/mural-client/src/index.ts
packages/mural-client/src/types.ts
packages/mural-picker/src/components/mural-create/index.tsx
packages/mural-picker/src/components/mural-picker/index.tsx

Update template type for searchCrossWorkspaceTemplates endpoint

[CWI-246] Update template type for searchCrossWorkspaceTemplates endpoint

---

packages/mural-client/src/types.ts

Added WorkspaceName Type to Mural

CWI-267 Added WorkspaceName Type to Mural

---

packages/mural-client/src/index.ts
packages/mural-client/src/types.ts
packages/mural-picker/src/components/card-list/index.tsx
packages/mural-picker/src/components/mural-picker-modal/index.tsx
packages/mural-picker/src/components/mural-picker/index.tsx
test/react/pages/mural-picker.tsx

Add MuralSummary type for search result
https://mural.atlassian.net/browse/CWI-267

[CWI-267] Add MuralSummary type for search result

---

packages/mural-client/src/index.ts

Add searchDefaultTemplates function

[CWI-287] Add searchDefaultTemplates function

---

packages/mural-picker/src/components/mural-create/index.tsx

CWI 638: Update 3 free mural message

---

packages/mural-picker/src/components/mural-picker/index.tsx

CWI-698 fix new mural bug

---

packages/mural-picker/src/components/mural-picker/index.tsx

https://mural.atlassian.net/browse/CWI-715
We updated the search to include searching for default templates.

CWI-715: updated search for default templates

---

packages/mural-canvas/src/lib/session-activation.ts

Add usage of freshcfg param to disable config cache

[CWI-1034] Add usage of freshcfg param to disable config cache

---

packages/mural-picker/src/components/mural-picker/index.tsx

Removing the disabling of the New Mural button while rooms is being loaded.

[CWI-91] Removing disabling of New mural button while loading rooms
